name: Deploy app to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: extractions/setup-just@v1
        with:
          just-version: 1.9

      # - name: Set stable toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable

      - name: Build
        run: |
          just build-app

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: app/dist
